apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grpc-demo-db
  namespace: applications
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grpc-demo-db
  data:
    - secretKey: username
      remoteRef:
        key: secret/data/api-security/grpc-demo-db
        property: username
    - secretKey: password
      remoteRef:
        key: secret/data/api-security/grpc-demo-db
        property: password
